import { FlywheelParams, FlywheelType } from "../types";

export interface Preset {
  name: string;
  name_zh: string;
  description: string;
  params: FlywheelParams;
}

export const PRESETS: Preset[] = [
  {
    name: "Standard Steel Flywheel",
    name_zh: "标准钢制飞轮",
    description: "通用工业储能",
    params: {
      r_o: 200,
      r_i: 40,
      thickness: 50,
      r_hub: 60,
      hub_thickness: 80,
      rpm_rated: 3000,
      rpm_max: 4500,
      rpm_min: 1500,
      n_points: 100,
      flywheel_type: FlywheelType.AnnularRing,
      material_id: "aisi_4340",
      safety_factor_yield: 1.5,
      safety_factor_fatigue: 1.5,
      safety_factor_burst: 2.0,
    },
  },
  {
    name: "High-Speed Composite",
    name_zh: "高速碳纤维飞轮",
    description: "高性能储能系统",
    params: {
      r_o: 150,
      r_i: 30,
      thickness: 30,
      r_hub: 45,
      hub_thickness: 50,
      rpm_rated: 20000,
      rpm_max: 30000,
      rpm_min: 10000,
      n_points: 100,
      flywheel_type: FlywheelType.AnnularRing,
      material_id: "carbon_fiber_t700",
      safety_factor_yield: 2.0,
      safety_factor_fatigue: 2.0,
      safety_factor_burst: 3.0,
    },
  },
  {
    name: "Solid Disk Low-Speed",
    name_zh: "低速实心飞轮",
    description: "教学演示",
    params: {
      r_o: 300,
      r_i: 0,
      thickness: 80,
      r_hub: 0,
      hub_thickness: 80,
      rpm_rated: 1000,
      rpm_max: 1500,
      rpm_min: 500,
      n_points: 100,
      flywheel_type: FlywheelType.SolidDisk,
      material_id: "c45_steel",
      safety_factor_yield: 1.5,
      safety_factor_fatigue: 1.5,
      safety_factor_burst: 2.0,
    },
  },
  {
    name: "Tapered Disk Optimized",
    name_zh: "锥形优化飞轮",
    description: "质量优化设计",
    params: {
      r_o: 180,
      r_i: 35,
      thickness: 25,
      r_hub: 50,
      hub_thickness: 70,
      rpm_rated: 5000,
      rpm_max: 7500,
      rpm_min: 2500,
      n_points: 100,
      flywheel_type: FlywheelType.TaperedDisk,
      material_id: "titanium_ti6al4v",
      safety_factor_yield: 1.8,
      safety_factor_fatigue: 1.8,
      safety_factor_burst: 2.5,
    },
  },
  {
    name: "Multi-Layer Heavy-Duty",
    name_zh: "多层重型飞轮",
    description: "重型工业储能",
    params: {
      r_o: 250,
      r_i: 50,
      thickness: 60,
      r_hub: 75,
      hub_thickness: 100,
      rpm_rated: 2000,
      rpm_max: 3000,
      rpm_min: 1000,
      n_points: 100,
      flywheel_type: FlywheelType.MultiLayerComposite,
      material_id: "aisi_4140",
      safety_factor_yield: 1.5,
      safety_factor_fatigue: 1.5,
      safety_factor_burst: 2.0,
    },
  },
  {
    name: "Constant Strength Profile",
    name_zh: "等强度轮廓飞轮",
    description: "高速储能",
    params: {
      r_o: 200,
      r_i: 40,
      thickness: 60,
      r_hub: 55,
      hub_thickness: 70,
      rpm_rated: 8000,
      rpm_max: 12000,
      rpm_min: 4000,
      n_points: 100,
      flywheel_type: FlywheelType.ConstantStrength,
      material_id: "maraging_18ni",
      safety_factor_yield: 2.0,
      safety_factor_fatigue: 2.0,
      safety_factor_burst: 3.0,
    },
  },
];
